# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f7de509b4490b23818b0f1d0e9f6fd5e8051b8fb0fcb7d1abc9b9aa97f0235f717313148afa330ed718dfd7c99b49eb76ed44f8858714f32bf6d1d420f45971

test:
  secret_key_base: ebe9464a0334d0b1c9e85a8ecf30393869b0ad587597003bcebad870f82570c239fb688474458b3aadd96583415a0cb85fb93d9a1caca603d9f700543df86699

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
